package io.github.xiaoailazy.coexistree.shared.enums;

public enum ErrorCode {
    SYSTEM_NOT_FOUND,
    SYSTEM_CODE_DUPLICATE,
    SYSTEM_CODE_EMPTY,
    SYSTEM_NAME_EMPTY,
    SYSTEM_HAS_DOCUMENTS,
    SYSTEM_OWNER_NOT_FOUND,

    USER_NOT_FOUND,
    USERNAME_EXISTS,
    CANNOT_DELETE_SUPER_ADMIN,
    CANNOT_MODIFY_SUPER_ADMIN_ROLE,

    DOCUMENT_NOT_FOUND,
    DUPLICATE_DOCUMENT,
    INVALID_FILE_TYPE,
    INVALID_FILE_CONTENT,
    FILE_SIZE_EXCEEDED,
    FILE_READ_ERROR,

    TREE_FILE_NOT_FOUND,
    TREE_FILE_INVALID,
    TREE_BUILD_FAILED,
    MARKDOWN_PARSE_ERROR,

    SYSTEM_TREE_NOT_READY,
    SYSTEM_TREE_NOT_FOUND,
    SYSTEM_TREE_WRITE_FAILED,

    CONVERSATION_NOT_FOUND,

    QA_FAILED,
    QUESTION_EMPTY,
    QUESTION_TOO_LONG,

    LLM_CALL_FAILED,
    LLM_TIMEOUT,

    JSON_SERIALIZE_ERROR,
    JSON_PARSE_ERROR,

    PERMISSION_DENIED,

    INTERNAL_ERROR
}
