-- Baseline Migration
-- 创建时间: 2026-03-28

-- =============================================
-- 1. 核心表
-- =============================================

-- 系统表
CREATE TABLE IF NOT EXISTS systems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_code VARCHAR(64) NOT NULL UNIQUE,
    system_name VARCHAR(128) NOT NULL,
    description CLOB,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- 文档表
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL,
    doc_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(512) NOT NULL,
    file_hash VARCHAR(128),
    content_type VARCHAR(32) NOT NULL,
    parse_status VARCHAR(32) NOT NULL,
    parse_error CLOB,
    doc_type VARCHAR(32) NOT NULL DEFAULT 'BASELINE',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- 对话表
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(64) NOT NULL UNIQUE,
    system_id BIGINT NOT NULL,
    title VARCHAR(255),
    last_response_id VARCHAR(64),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_conversations_system_id ON conversations(system_id);

-- 消息表
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(64) NOT NULL,
    role VARCHAR(20) NOT NULL,
    content CLOB NOT NULL,
    llm_response_id VARCHAR(64),
    thinking CLOB,
    citations CLOB,
    metadata CLOB,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);

-- =============================================
-- 2. 知识树相关表
-- =============================================

-- 系统知识树表
CREATE TABLE IF NOT EXISTS system_knowledge_trees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL UNIQUE,
    tree_file_path VARCHAR(512) NOT NULL,
    tree_version INT NOT NULL DEFAULT 1,
    description CLOB,
    node_count INT NOT NULL DEFAULT 0,
    tree_status VARCHAR(32) NOT NULL DEFAULT 'EMPTY',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- 文档知识树表
CREATE TABLE IF NOT EXISTS document_trees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE,
    tree_file_path VARCHAR(512) NOT NULL,
    doc_description CLOB,
    node_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- 系统知识树快照表
CREATE TABLE IF NOT EXISTS system_tree_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL,
    snapshot_name VARCHAR(50) NOT NULL,
    tree_json TEXT NOT NULL,
    triggered_by_doc_id BIGINT,
    triggered_by VARCHAR(100),
    node_count INT,
    is_pinned BOOLEAN DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_snapshots_system_id ON system_tree_snapshots(system_id);
CREATE INDEX IF NOT EXISTS idx_snapshots_created_at ON system_tree_snapshots(created_at);

-- =============================================
-- 3. 日志表
-- =============================================

-- 处理日志表
CREATE TABLE IF NOT EXISTS process_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(32) NOT NULL,
    entity_id BIGINT NOT NULL,
    process_stage VARCHAR(64) NOT NULL,
    process_status VARCHAR(32) NOT NULL,
    message CLOB,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_process_logs_entity ON process_logs(entity_type, entity_id);

-- =============================================
-- 4. QA 日志表
-- =============================================

CREATE TABLE IF NOT EXISTS qa_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL,
    document_id BIGINT,
    conversation_id VARCHAR(64),
    question CLOB NOT NULL,
    search_nodes CLOB,
    answer CLOB,
    citations CLOB,
    grounded BOOLEAN NOT NULL,
    response_ms INT,
    created_at TIMESTAMP NOT NULL
);
