-- PostgreSQL baseline schema

CREATE TABLE systems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_code VARCHAR(64) NOT NULL UNIQUE,
    system_name VARCHAR(128) NOT NULL,
    description TEXT,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by BIGINT,
    is_public BOOLEAN DEFAULT FALSE
);

CREATE INDEX idx_systems_created_by ON systems(created_by);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL,
    doc_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    file_content TEXT NOT NULL,
    file_hash VARCHAR(128),
    content_hash VARCHAR(64),
    content_type VARCHAR(32) NOT NULL,
    parse_status VARCHAR(32) NOT NULL,
    parse_error TEXT,
    doc_type VARCHAR(32) NOT NULL DEFAULT 'BASELINE',
    security_level INTEGER NOT NULL DEFAULT 1,
    uploaded_by BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_documents_system_hash ON documents(system_id, content_hash);
CREATE INDEX idx_documents_security_level ON documents(security_level);
CREATE INDEX idx_documents_uploaded_by ON documents(uploaded_by);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(64) NOT NULL UNIQUE,
    system_id BIGINT NOT NULL,
    title VARCHAR(255),
    last_response_id VARCHAR(64),
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_conversations_system_id ON conversations(system_id);

CREATE TABLE messages_archived (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(64) NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    llm_response_id VARCHAR(64),
    thinking TEXT,
    citations TEXT,
    metadata TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_messages_conversation_id ON messages_archived(conversation_id);

CREATE TABLE system_knowledge_trees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL UNIQUE,
    tree_json TEXT NOT NULL,
    tree_version INTEGER NOT NULL DEFAULT 1,
    description TEXT,
    node_count INTEGER NOT NULL DEFAULT 0,
    tree_status VARCHAR(32) NOT NULL DEFAULT 'EMPTY',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE document_trees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE,
    tree_json TEXT NOT NULL,
    doc_description TEXT,
    node_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE system_tree_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL,
    snapshot_name VARCHAR(50) NOT NULL,
    tree_json TEXT NOT NULL,
    triggered_by_doc_id BIGINT,
    triggered_by VARCHAR(100),
    node_count INTEGER,
    is_pinned BOOLEAN DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX idx_snapshots_system_id ON system_tree_snapshots(system_id);
CREATE INDEX idx_snapshots_created_at ON system_tree_snapshots(created_at);

CREATE TABLE doc_process_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(32) NOT NULL,
    entity_id BIGINT NOT NULL,
    process_stage VARCHAR(64) NOT NULL,
    process_status VARCHAR(32) NOT NULL,
    message TEXT,
    created_at TIMESTAMP NOT NULL,
    correlation_id VARCHAR(64),
    elapsed_ms BIGINT
);

CREATE INDEX idx_process_logs_entity ON doc_process_logs(entity_type, entity_id);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(128) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    role VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    last_login_at TIMESTAMP
);

CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_created_by ON users(created_by);

CREATE TABLE system_user_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    relation_type VARCHAR(32) NOT NULL,
    view_level INTEGER NOT NULL DEFAULT 1,
    assigned_by BIGINT,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_system_user UNIQUE (system_id, user_id)
);

CREATE INDEX idx_sys_user_mappings_system_id ON system_user_mappings(system_id);
CREATE INDEX idx_sys_user_mappings_user_id ON system_user_mappings(user_id);
CREATE INDEX idx_sys_user_mappings_type ON system_user_mappings(relation_type);

CREATE TABLE doc_llm_call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_log_id BIGINT,
    model VARCHAR(64) NOT NULL,
    temperature DOUBLE PRECISION,
    input_tokens BIGINT,
    output_tokens BIGINT,
    reasoning_tokens BIGINT,
    total_tokens BIGINT,
    elapsed_ms BIGINT NOT NULL,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_doc_llm_call_logs_process_log_id ON doc_llm_call_logs(process_log_id);
CREATE INDEX idx_doc_llm_call_logs_created_at ON doc_llm_call_logs(created_at);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation_id VARCHAR(64),
    user_id BIGINT,
    username VARCHAR(64),
    action_type VARCHAR(32) NOT NULL,
    entity_type VARCHAR(32),
    entity_id BIGINT,
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    detail TEXT,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_logs_user_time ON audit_logs(user_id, created_at);
CREATE INDEX idx_audit_logs_action_time ON audit_logs(action_type, created_at);

CREATE TABLE conversation_runs (
    id BIGINT PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    trace_id VARCHAR(64) NOT NULL,
    conversation_id VARCHAR(64) NOT NULL,
    trigger_message_id BIGINT,
    user_id BIGINT,
    system_id BIGINT,
    root_agent_name VARCHAR(128),
    request_text TEXT,
    final_answer TEXT,
    status VARCHAR(16) NOT NULL,
    error_code VARCHAR(64),
    error_message TEXT,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    duration_ms BIGINT,
    correlation_id VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_runs_conversation_time ON conversation_runs(conversation_id, started_at DESC);
CREATE INDEX idx_runs_run_id ON conversation_runs(run_id);
CREATE INDEX idx_runs_trace_id ON conversation_runs(trace_id);
CREATE INDEX idx_runs_correlation_id ON conversation_runs(correlation_id);
CREATE INDEX idx_runs_status_time ON conversation_runs(status, started_at DESC);

CREATE TABLE observation_spans (
    id BIGINT PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    span_id VARCHAR(64) NOT NULL,
    parent_span_id VARCHAR(64),
    run_id VARCHAR(64) NOT NULL,
    conversation_id VARCHAR(64) NOT NULL,
    span_type VARCHAR(32) NOT NULL,
    span_name VARCHAR(128) NOT NULL,
    agent_name VARCHAR(128),
    tool_name VARCHAR(128),
    model_name VARCHAR(128),
    model_version VARCHAR(128),
    status VARCHAR(16) NOT NULL,
    input_payload TEXT,
    output_payload TEXT,
    attributes TEXT,
    error_payload TEXT,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    duration_ms BIGINT,
    depth INTEGER,
    sequence_no BIGINT,
    correlation_id VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_spans_run_time ON observation_spans(run_id, started_at, id);
CREATE INDEX idx_spans_conversation_time ON observation_spans(conversation_id, started_at, id);
CREATE INDEX idx_spans_span_id ON observation_spans(span_id);
CREATE INDEX idx_spans_parent ON observation_spans(parent_span_id);
CREATE INDEX idx_spans_type_time ON observation_spans(span_type, started_at DESC);
CREATE INDEX idx_spans_agent_time ON observation_spans(agent_name, started_at DESC);
CREATE INDEX idx_spans_tool_time ON observation_spans(tool_name, started_at DESC);
CREATE INDEX idx_spans_model_time ON observation_spans(model_name, started_at DESC);

CREATE TABLE span_events (
    id BIGINT PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    span_id VARCHAR(64) NOT NULL,
    conversation_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    event_name VARCHAR(128),
    payload JSONB,
    occurred_at TIMESTAMP NOT NULL,
    sequence_no BIGINT,
    correlation_id VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_events_run_time ON span_events(run_id, occurred_at, id);
CREATE INDEX idx_events_span_time ON span_events(span_id, occurred_at, id);
CREATE INDEX idx_events_conversation_time ON span_events(conversation_id, occurred_at, id);
CREATE INDEX idx_events_type_time ON span_events(event_type, occurred_at DESC);

CREATE TABLE adk_sessions (
    id VARCHAR(64) PRIMARY KEY,
    app_name VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    state_json TEXT,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL
);

CREATE INDEX idx_adk_sessions_app_user ON adk_sessions(app_name, user_id);

CREATE TABLE adk_events (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL REFERENCES adk_sessions(id),
    app_name VARCHAR(128) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    author VARCHAR(128),
    event_json TEXT NOT NULL,
    timestamp BIGINT NOT NULL
);

CREATE INDEX idx_adk_events_session ON adk_events(session_id);
CREATE INDEX idx_adk_events_app_user ON adk_events(app_name, user_id);
