-- Feature-tree refactor: core DDL for change records and document/tree/snapshot alignment.
-- 前提：不考虑历史数据兼容；与树/快照相关的旧行可按段内说明清空。documents 行保留并做列回填。

-- ---------------------------------------------------------------------------
-- 1) system_change_records（需求 §17.4）
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_change_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL REFERENCES systems(id),
    title VARCHAR(255) NOT NULL,
    summary TEXT,
    tree_version_before INT,
    tree_version_after INT,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_change_system_created ON system_change_records (system_id, created_at);
CREATE INDEX IF NOT EXISTS idx_change_tree_version ON system_change_records (system_id, tree_version_after);

-- ---------------------------------------------------------------------------
-- 2) documents — 新列 + 数据迁移 + 索引
-- ---------------------------------------------------------------------------
ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS change_record_id BIGINT REFERENCES system_change_records (id),
    ADD COLUMN IF NOT EXISTS doc_content_type VARCHAR(32),
    ADD COLUMN IF NOT EXISTS markdown_content TEXT,
    ADD COLUMN IF NOT EXISTS tree_build_status VARCHAR(32),
    ADD COLUMN IF NOT EXISTS merge_status VARCHAR(32);

UPDATE documents
SET markdown_content = file_content
WHERE markdown_content IS NULL;

UPDATE documents
SET doc_content_type = CASE doc_type
    WHEN 'BASELINE' THEN 'REQUIREMENT'
    WHEN 'CHANGE' THEN 'DESIGN'
    ELSE 'GENERAL'
END
WHERE doc_content_type IS NULL;

CREATE INDEX IF NOT EXISTS idx_doc_change_record ON documents (change_record_id);
CREATE INDEX IF NOT EXISTS idx_doc_system_type ON documents (system_id, doc_content_type);

-- ---------------------------------------------------------------------------
-- 3) document_trees — system_id 回填
-- ---------------------------------------------------------------------------
ALTER TABLE document_trees
    ADD COLUMN IF NOT EXISTS system_id BIGINT REFERENCES systems (id);

UPDATE document_trees dt
SET system_id = d.system_id
FROM documents d
WHERE d.id = dt.document_id
  AND dt.system_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_doc_tree_system ON document_trees (system_id);

-- ---------------------------------------------------------------------------
-- 4) system_tree_snapshots — §17.3 列 + JSONB；旧数据冲突则清空快照表
-- ---------------------------------------------------------------------------
TRUNCATE TABLE system_tree_snapshots;

ALTER TABLE system_tree_snapshots
    ADD COLUMN IF NOT EXISTS tree_version INT,
    ADD COLUMN IF NOT EXISTS related_change_record_id BIGINT REFERENCES system_change_records (id);

ALTER TABLE system_tree_snapshots
    ALTER COLUMN tree_json TYPE JSONB USING tree_json::jsonb;

CREATE UNIQUE INDEX IF NOT EXISTS uk_system_snapshot_version ON system_tree_snapshots (system_id, tree_version);
