-- System-User mapping table
CREATE TABLE IF NOT EXISTS system_user_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    relation_type VARCHAR(32) NOT NULL,
    view_level INT NOT NULL DEFAULT 1,
    assigned_by BIGINT,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_system_user (system_id, user_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sys_user_mappings_system_id ON system_user_mappings(system_id);
CREATE INDEX IF NOT EXISTS idx_sys_user_mappings_user_id ON system_user_mappings(user_id);
CREATE INDEX IF NOT EXISTS idx_sys_user_mappings_type ON system_user_mappings(relation_type);

-- Add created_by to systems table
ALTER TABLE systems ADD COLUMN IF NOT EXISTS created_by BIGINT;
ALTER TABLE systems ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_systems_created_by ON systems(created_by);
