ALTER TABLE llm_calls ALTER COLUMN input_tokens SET DATA TYPE BIGINT;
ALTER TABLE llm_calls ALTER COLUMN output_tokens SET DATA TYPE BIGINT;
ALTER TABLE llm_calls ALTER COLUMN reasoning_tokens SET DATA TYPE BIGINT;
ALTER TABLE llm_calls ALTER COLUMN total_tokens SET DATA TYPE BIGINT;
