/** 与后端 ErrorCode 枚举 name() 字符串一致 */
export const ErrorCode = Object.freeze({
  APPLY_PRECONDITION_FAILED: 'APPLY_PRECONDITION_FAILED',
  UPDATE_PLAN_ORDER_INVALID: 'UPDATE_PLAN_ORDER_INVALID',
  UPDATE_PLAN_DEPENDENCY_FAILED: 'UPDATE_PLAN_DEPENDENCY_FAILED',
  UPDATE_PLAN_OPERATION_NOT_SUPPORTED: 'UPDATE_PLAN_OPERATION_NOT_SUPPORTED',
  BASE_TREE_VERSION_MISMATCH: 'BASE_TREE_VERSION_MISMATCH',
  DOCUMENT_REFERENCE_INVALID: 'DOCUMENT_REFERENCE_INVALID',
  LLM_RETRIES_EXHAUSTED: 'LLM_RETRIES_EXHAUSTED',
  CHANGE_INPUT_CHANGED: 'CHANGE_INPUT_CHANGED',
  OPERATION_NOT_SUPPORTED: 'OPERATION_NOT_SUPPORTED',
});
